### ISSUE TITLE
Pip Install 3.10 Failure

### ISSUE THREAD

**Issue by AdventuresOfMar** [bsl-tools/bsl#69]
Hello!
Hope all is well thanks for the library.  Im attempting to do a pip install on python 3.10 and it keeps hanging on the getting meta process. Any ideas? I also tried pip install with verbose and it looks like theres a license agreement that needs to be accepted but after typing yes nothing happens

**Comment by mscheltienne** [comment]
Hello, sadly nothing comes to mind. I quickly installed [Python 3.10.8](https://www.python.org/downloads/release/python-3108/) to give it a shot, and the `pip` install worked fine. 

Which version of Python are you using? On which OS? Could you copy/paste a console output?
Could you also try an install from source: `pip install git+https://github.com/bsl-tools/bsl`

**Comment by AdventuresOfMar** [comment]
Ah weird, hmm thanks for the help @mscheltienne 

For python version:
(venv) (base) AdventuresOfMar@Lovlad ProjectCrypt % python --version
Python 3.10.8


Im using Mac OS. Currently Im using python as my ide and running the install through venv. The normal pip install gives me this and hangs hereCollecting git+https://github.com/bsl-tools/bsl
  Cloning https://github.com/bsl-tools/bsl to /private/var/folders/ps/p3l02b0n70g61gqsyhz8g2fm0000gn/T/pip-req-build-185boms2
  Running command git clone --filter=blob:none --quiet https://github.com/bsl-tools/bsl /private/var/folders/ps/p3l02b0n70g61gqsyhz8g2fm0000gn/T/pip-req-build-185boms2
  Resolved https://github.com/bsl-tools/bsl to commit 09aa4fc4c5b085a40b5e9a7a3b53230c6325e610
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Collecting pyqtgraph
  Using cached pyqtgraph-0.13.1-py3-none-any.whl (966 kB)
Collecting mne>=1.0.0
  Using cached mne-1.2.0-py3-none-any.whl (7.6 MB)
Collecting PyQt5
  Using cached PyQt5-5.15.7.tar.gz (3.2 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... \



For pip install verbose Im getting
(venv) (base) AdventuresOfMar@Lovlad ProjectCrypt % pip install --verbose git+https://github.com/bsl-tools/bsl
Using pip 22.2.2 from /Users/AdventuresOfMar/PycharmProjects/ProjectCrypt/venv/lib/python3.10/site-packages/pip (python 3.10)
Collecting git+https://github.com/bsl-tools/bsl
  Cloning https://github.com/bsl-tools/bsl to /private/var/folders/ps/p3l02b0n70g61gqsyhz8g2fm0000gn/T/pip-req-build-erbv_mml
  Running command git version
  git version 2.33.0
  Running command git clone --filter=blob:none https://github.com/bsl-tools/bsl /private/var/folders/ps/p3l02b0n70g61gqsyhz8g2fm0000gn/T/pip-req-build-erbv_mml
  Cloning into '/private/var/folders/ps/p3l02b0n70g61gqsyhz8g2fm0000gn/T/pip-req-build-erbv_mml'...
  Updating files:   1% (2/151)
  Updating files:   2% (4/151)
  Updating files:   3% (5/151)
  Updating files:   4% (7/151)
  Updating files:   5% (8/151)
  Updating files:   6% (10/151)
  Updating files:   7% (11/151)
  Updating files:   8% (13/151)
  Updating files:   9% (14/151)
  Updating files:  10% (16/151)
  Updating files:  11% (17/151)
  Updating files:  12% (19/151)
  Updating files:  13% (20/151)
  Updating files:  14% (22/151)
  Updating files:  15% (23/151)
  Updating files:  16% (25/151)
  Updating files:  17% (26/151)
  Updating files:  18% (28/151)
  Updating files:  19% (29/151)
  Updating files:  20% (31/151)
  Updating files:  21% (32/151)
  Updating files:  22% (34/151)
  Updating files:  23% (35/151)
  Updating files:  24% (37/151)
  Updating files:  25% (38/151)
  Updating files:  26% (40/151)
  Updating files:  27% (41/151)
  Updating files:  28% (43/151)
  Updating files:  29% (44/151)
  Updating files:  30% (46/151)
  Updating files:  31% (47/151)
  Updating files:  32% (49/151)
  Updating files:  33% (50/151)
  Updating files:  34% (52/151)
  Updating files:  35% (53/151)
  Updating files:  36% (55/151)
  Updating files:  37% (56/151)
  Updating files:  38% (58/151)
  Updating files:  39% (59/151)
  Updating files:  40% (61/151)
  Updating files:  41% (62/151)
  Updating files:  42% (64/151)
  Updating files:  43% (65/151)
  Updating files:  44% (67/151)
  Updating files:  45% (68/151)
  Updating files:  46% (70/151)
  Updating files:  47% (71/151)
  Updating files:  48% (73/151)
  Updating files:  49% (74/151)
  Updating files:  50% (76/151)
  Updating files:  51% (78/151)
  Updating files:  52% (79/151)
  Updating files:  53% (81/151)
  Updating files:  54% (82/151)
  Updating files:  55% (84/151)
  Updating files:  56% (85/151)
  Updating files:  57% (87/151)
  Updating files:  58% (88/151)
  Updating files:  59% (90/151)
  Updating files:  60% (91/151)
  Updating files:  61% (93/151)
  Updating files:  62% (94/151)
  Updating files:  63% (96/151)
  Updating files:  64% (97/151)
  Updating files:  65% (99/151)
  Updating files:  66% (100/151)
  Updating files:  67% (102/151)
  Updating files:  68% (103/151)
  Updating files:  69% (105/151)
  Updating files:  70% (106/151)
  Updating files:  71% (108/151)
  Updating files:  72% (109/151)
  Updating files:  73% (111/151)
  Updating files:  74% (112/151)
  Updating files:  75% (114/151)
  Updating files:  76% (115/151)
  Updating files:  77% (117/151)
  Updating files:  78% (118/151)
  Updating files:  79% (120/151)
  Updating files:  80% (121/151)
  Updating files:  81% (123/151)
  Updating files:  82% (124/151)
  Updating files:  83% (126/151)
  Updating files:  84% (127/151)
  Updating files:  85% (129/151)
  Updating files:  86% (130/151)
  Updating files:  87% (132/151)
  Updating files:  88% (133/151)
  Updating files:  89% (135/151)
  Updating files:  90% (136/151)
  Updating files:  91% (138/151)
  Updating files:  92% (139/151)
  Updating files:  93% (141/151)
  Updating files:  94% (142/151)
  Updating files:  95% (144/151)
  Updating files:  96% (145/151)
  Updating files:  97% (147/151)
  Updating files:  98% (148/151)
  Updating files:  99% (150/151)
  Updating files: 100% (151/151)
  Updating files: 100% (151/151), done.
  Running command git rev-parse HEAD
  09aa4fc4c5b085a40b5e9a7a3b53230c6325e610
  Resolved https://github.com/bsl-tools/bsl to commit 09aa4fc4c5b085a40b5e9a7a3b53230c6325e610
  Running command git rev-parse HEAD
  09aa4fc4c5b085a40b5e9a7a3b53230c6325e610
  Running command pip subprocess to install build dependencies
  Collecting setuptools>=61.0.0
    Using cached setuptools-65.5.0-py3-none-any.whl (1.2 MB)
  Installing collected packages: setuptools
  Successfully installed setuptools-65.5.0
  Installing build dependencies ... done
  Running command Getting requirements to build wheel
  /private/var/folders/ps/p3l02b0n70g61gqsyhz8g2fm0000gn/T/pip-build-env-qt5bab3e/overlay/lib/python3.10/site-packages/setuptools/config/pyprojecttoml.py:108: _BetaConfiguration: Support for `[tool.setuptools]` in `pyproject.toml` is still *beta*.
    warnings.warn(msg, _BetaConfiguration)
  running egg_info
  writing bsl.egg-info/PKG-INFO
  writing dependency_links to bsl.egg-info/dependency_links.txt
  writing entry points to bsl.egg-info/entry_points.txt
  writing requirements to bsl.egg-info/requires.txt
  writing top-level names to bsl.egg-info/top_level.txt
  reading manifest file 'bsl.egg-info/SOURCES.txt'
  adding license file 'LICENSE'
  Getting requirements to build wheel ... done
  Running command pip subprocess to install backend dependencies
  Collecting wheel
    Using cached wheel-0.37.1-py2.py3-none-any.whl (35 kB)
  Installing collected packages: wheel
  Successfully installed wheel-0.37.1
  Installing backend dependencies ... done
  Running command Preparing metadata (pyproject.toml)
  /private/var/folders/ps/p3l02b0n70g61gqsyhz8g2fm0000gn/T/pip-build-env-qt5bab3e/overlay/lib/python3.10/site-packages/setuptools/config/pyprojecttoml.py:108: _BetaConfiguration: Support for `[tool.setuptools]` in `pyproject.toml` is still *beta*.
    warnings.warn(msg, _BetaConfiguration)
  running dist_info
  writing /private/var/folders/ps/p3l02b0n70g61gqsyhz8g2fm0000gn/T/pip-modern-metadata-st7c8bc_/bsl.egg-info/PKG-INFO
  writing dependency_links to /private/var/folders/ps/p3l02b0n70g61gqsyhz8g2fm0000gn/T/pip-modern-metadata-st7c8bc_/bsl.egg-info/dependency_links.txt
  writing entry points to /private/var/folders/ps/p3l02b0n70g61gqsyhz8g2fm0000gn/T/pip-modern-metadata-st7c8bc_/bsl.egg-info/entry_points.txt
  writing requirements to /private/var/folders/ps/p3l02b0n70g61gqsyhz8g2fm0000gn/T/pip-modern-metadata-st7c8bc_/bsl.egg-info/requires.txt
  writing top-level names to /private/var/folders/ps/p3l02b0n70g61gqsyhz8g2fm0000gn/T/pip-modern-metadata-st7c8bc_/bsl.egg-info/top_level.txt
  reading manifest file '/private/var/folders/ps/p3l02b0n70g61gqsyhz8g2fm0000gn/T/pip-modern-metadata-st7c8bc_/bsl.egg-info/SOURCES.txt'
  adding license file 'LICENSE'
  creating '/private/var/folders/ps/p3l02b0n70g61gqsyhz8g2fm0000gn/T/pip-modern-metadata-st7c8bc_/bsl-0.6.0.dev0.dist-info'
  adding license file "LICENSE" (matched pattern "LICEN[CS]E*")
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: numpy in ./venv/lib/python3.10/site-packages (from bsl==0.6.0.dev0) (1.23.3)
Collecting pyqtgraph
  Using cached pyqtgraph-0.13.1-py3-none-any.whl (966 kB)
  Link requires a different Python (3.10.8 not in: '>=3.7,<3.10'): https://files.pythonhosted.org/packages/99/f1/c00d6be56e1a718a3068079e3ec8ce044d7179345280f6a3f5066068af0d/scipy-1.6.2.tar.gz (from https://pypi.org/simple/scipy/) (requires-python:>=3.7,<3.10)
  Link requires a different Python (3.10.8 not in: '>=3.7,<3.10'): https://files.pythonhosted.org/packages/fe/fd/8704c7b7b34cdac850485e638346025ca57c5a859934b9aa1be5399b33b7/scipy-1.6.3.tar.gz (from https://pypi.org/simple/scipy/) (requires-python:>=3.7,<3.10)
  Link requires a different Python (3.10.8 not in: '>=3.7,<3.10'): https://files.pythonhosted.org/packages/8e/e1/ba481fb2154410f9c5a2d875695873597a7b1bea8c7f87cf444479c3260c/scipy-1.7.0rc1.tar.gz (from https://pypi.org/simple/scipy/) (requires-python:>=3.7,<3.10)
  Link requires a different Python (3.10.8 not in: '>=3.7,<3.10'): https://files.pythonhosted.org/packages/a2/ae/ef8b23f5383403a597f2f79df44124a9b8f011a8beb1bca4c6b663a61d15/scipy-1.7.0rc2.tar.gz (from https://pypi.org/simple/scipy/) (requires-python:>=3.7,<3.10)
  Link requires a different Python (3.10.8 not in: '>=3.7,<3.10'): https://files.pythonhosted.org/packages/bb/bb/944f559d554df6c9adf037aa9fc982a9706ee0e96c0d5beac701cb158900/scipy-1.7.0.tar.gz (from https://pypi.org/simple/scipy/) (requires-python:>=3.7,<3.10)
  Link requires a different Python (3.10.8 not in: '>=3.7,<3.10'): https://files.pythonhosted.org/packages/47/33/a24aec22b7be7fdb10ec117a95e1e4099890d8bbc6646902f443fc7719d1/scipy-1.7.1.tar.gz (from https://pypi.org/simple/scipy/) (requires-python:>=3.7,<3.10)
Collecting scipy
  Using cached scipy-1.9.2-cp310-cp310-macosx_12_0_arm64.whl (28.5 MB)
Collecting PyQt5
  Using cached PyQt5-5.15.7.tar.gz (3.2 MB)
  Running command pip subprocess to install build dependencies
  Collecting sip<7,>=6.4
    Using cached sip-6.7.2-cp37-abi3-macosx_10_9_universal2.whl (739 kB)
  Collecting PyQt-builder<2,>=1.9
    Using cached PyQt_builder-1.14.0-py3-none-any.whl (3.7 MB)
  Collecting ply
    Using cached ply-3.11-py2.py3-none-any.whl (49 kB)
  Collecting packaging
    Using cached packaging-21.3-py3-none-any.whl (40 kB)
  Collecting setuptools
    Using cached setuptools-65.5.0-py3-none-any.whl (1.2 MB)
  Collecting toml
    Using cached toml-0.10.2-py2.py3-none-any.whl (16 kB)
  Collecting pyparsing!=3.0.5,>=2.0.2
    Using cached pyparsing-3.0.9-py3-none-any.whl (98 kB)
  Installing collected packages: ply, toml, setuptools, pyparsing, packaging, sip, PyQt-builder
  Successfully installed PyQt-builder-1.14.0 packaging-21.3 ply-3.11 pyparsing-3.0.9 setuptools-65.5.0 sip-6.7.2 toml-0.10.2
  Installing build dependencies ... done
  Running command Getting requirements to build wheel
  Getting requirements to build wheel ... done
  Running command Preparing metadata (pyproject.toml)
  Querying qmake about your Qt installation...
  This is the GPL version of PyQt 5.15.7 (licensed under the GNU General Public License) for Python 3.10.8 on darwin.

  Type 'L' to view the license.
  Type 'yes' to accept the terms of the license.
  Type 'no' to decline the terms of the license.

**Comment by mscheltienne** [comment]
That's a weird one..

Let's try a couple of points:
- update `pip`, `setuptools` and ``wheel`: `pip install --upgrade pip setuptools wheel`
- try installing PyQt5 by itself: `pip install pyqt5`

Are those 2 commands working?

**Comment by AdventuresOfMar** [comment]
Ah super weird, I'm not sure what happened but cleared out my python completed and reinstalled and it looks like a problem with pyqt5 now. Thanks so much !

**Comment by AdventuresOfMar** [comment]
AH for help on other Mac M1 users: https://stackoverflow.com/questions/65447314/attributeerror-module-sipbuild-api-has-no-attribute-prepare-metadata-for-bui

**Comment by mscheltienne** [comment]
Oh alright, it was a M1 issue with PyQt5, thanks for the head's up!

Part of the refactor to come next year is to replace `PyQt5` with `qtpy` which makes the GUI Qt-abnoxious. It will then be possible to use `PyQt6` or `PySide2` instead which are more recent and probably better for recent M1 machines.
